name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fmt
      run: cargo fmt -- --check
    - name: rust-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: --lib
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
    - name: run warp test
      run: cargo test --test warp
    - name: setup-firefox
      uses: browser-actions/setup-firefox@latest
    - name: setup-geckodriver
      uses: browser-actions/setup-geckodriver@latest
    - name: run gekodriver test
      run: | 
        geckodriver -b ./scripts/headless-firefox.sh &
        cargo test --test browser_client
        pkill geckodriver
    - name: setup-chrome
      uses: browser-actions/setup-chrome@latest
    - name: setup-chromedrivr
      uses: nanasess/setup-chromedriver@master
    - name: run chromedriver test
      run: |
        DISPLAY=:99 chromedriver --url-base=/wd/hub --port=4444 &
        cargo test --test browser_client
        pkill chromedriver
